replicaCount: 3

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: my-app-sa  # or any name you'd like
